### ISSUE TITLE
Collision detection between different source layers

### ISSUE THREAD

**Issue by hasan9206** [tangrams/tangram#365] opened 2016-07-26 12:35 UTC
Hope you all are doing well! I am facing an issue detecting collisions between labels and icons when the data is in different source layers. I have made my POIs into a separate source layer as I wanted to be able to update them on a regular basis to keep them up to date, the rest of my data is in one source layer.

When I use a different source layer for POIs, i get this:
![1](https://cloud.githubusercontent.com/assets/7081695/17137916/2cd9f7d8-5357-11e6-88bd-a1181ae55d88.png)

The collisions between the POI icons and labels and other labels (Area names, street labels) are not detected, they overlap.

I have them defined in separate source layers:

<pre>
sources:
    local:
        type: GeoJSON
        url:  http://127.0.0.1:8002/composite/{z}/{x}/{y}.json
        min_zoom: 1
        max_zoom: 21
    local-pois:
        type: GeoJSON
        url:  http://127.0.0.1:8002/pois/{z}/{x}/{y}.json
        min_zoom: 10
        max_zoom: 19 
</pre>

When I use a single source, Tangram works as it should:
![11](https://cloud.githubusercontent.com/assets/7081695/17137929/3d969c16-5357-11e6-8043-d6c6f966dc30.png)

How can I stop the labels from overlapping when the source layer is different?

**Comment by dmvaldman** [comment] 2016-07-26 15:08
Thanks for submitting this! I've confirmed the behavior. I'll be looking into it. @bcamper

**Comment by bcamper** [comment] 2016-07-26 17:52
Ah yeah thanks for the report. While not intentional, this is a limitation of the current architecture:

Each data source builds its own tiles. This is because data sources can have different `max_zoom` values, which means there isn't always a 1:1 correlation of tiles between data sources, e.g. a z16 tile in source A with `max_zoom: 16` will cover the same geographic area as 16 individual tiles at z18 in source B (with no `max_zoom`). For this reason, the tiles are built per-data source, and have no direct knowledge of each other, making collision between them difficult to anticipate and manage.

@dmvaldman: I'll give this some thought, but it may need to wait until we re-architect to enable collision in screen-space on the main thread (assuming we go down that route). This would make it easier for collision boxes originating from many entities (different styles/tiles/data sources) to be pooled in one place. On the other hand we've also discussed only doing main thread / screen-space collisions for a subset of labels, like those that cross tile boundaries. So depending on this might not make sense either.

@hasan9206 thanks again, we'll look into the best way to solve this! But unfortunately the solution may not be near-term (unless a surprise solution is found ;)

**Comment by bcamper** [comment] 2016-07-26 17:52
@karimnaaji can you confirm that we don't (I think?) have this issue in ES because labels from all sources will be combined into one set and collided in screen-space?

**Comment by karimnaaji** [comment] 2016-07-26 18:04
Right, this can't happen on ES.

**Comment by bcamper** [comment] 2016-07-26 18:14
@karimnaaji 👍

**Comment by hasan9206** [comment] 2016-07-27 05:10
@dmvaldman @bcamper Thanks for the quick reply as always! really appreciate it.

Until a solution is found, I'll see if I can combine all the labels into one source (like @bcamper  said happens in ES) to detect collisions.

**Comment by hasan9206** [comment] 2017-04-27 07:13
@nvkelso @bcamper Any progress on this? Should I just move all my labels in a single source?

**Comment by bcamper** [comment] 2017-04-27 13:21
I would love to fix this but no progress currently (ideally within the next few months?). If it's practical for you to move your data into a single source, yes! ;)

**Comment by sheikh-iffi** [comment] 2017-06-05 05:52
@bcamper any estimate on when this issue will be resolved?

**Comment by bcamper** [comment] 2017-06-05 14:05
Unfortunately no. I realize it's a high impact issue for some apps, but it's going to require a significant refactor. We had expected to work on it in this time range, but had to reprioritize to accommodate some other needs. So it remains on my radar as an important thing to fix, but I can't provide an ETA right now.

**Comment by bcamper** [comment] 2017-12-03 03:14
Working on this for v0.15.0.

**Comment by jschleuss** [comment] 2017-12-03 03:53
Where do I send the chocolates?

**Comment by bcamper** [comment] 2018-02-19 22:07
Hello everyone... this is still happening ;) See PR in #633. 😎

**Comment by meetar** [comment] 2018-05-16 22:14
Added test with https://github.com/tangrams/differ-tests/commit/0438f661eb734ff11ba655e32565f8c66e0b5a49 :

http://tangrams.github.io/tangram-frame/?url=https://tangrams.github.io/differ-tests/unit-tests/points/points-source-collide.yaml&lib=0.15#1/0/0

Closing as fixed 👌

**Closed by meetar** 2018-05-16 22:14 UTC
Labels: bug
