### ISSUE TITLE
Short lines looks like triangles

### ISSUE THREAD

**Issue by donflopez** [tangrams/tangram#457] opened 2016-11-29 08:48 UTC
**TO REPRODUCE THE ISSUE, FOLLOW THESE STEPS:**

- Clone our [tangram-carto](https://github.com/CartoDB/tangram-carto) library
- Go to advanved-demo branch
- npm install or yarn
- npm start or yarn start
- open the demo in the browser
- paste this url in the input -> https://isabeldb.carto.com/builder/ed41d2ea-9c52-11e6-9684-0ee66e2c9693/embed
- press GO button
- make zoom in Manhattan

**RESULT:**

Some short lines seems like triangles, (maybe some reduction/collision algorithm?)

![screen shot 2016-11-29 at 09 25 21](https://cloud.githubusercontent.com/assets/463462/20702387/e3afd9c8-b617-11e6-978d-2a94dc9c3b25.png)

**EXPECTED RESULT:**

Render all the lines correctly, like the longer ones.

**ENVIRONMENT:**

Chrome Version 54.0.2840.98 (64-bit)

**OTHER:**

Is there any configuration that I'm missing?

Thank you!!!

**Comment by dmvaldman** [comment] 2016-11-29 15:43
Will check if this is due to a bug in our line building. Could be that for a line of one segment there is an error.

**Comment by bcamper** [comment] 2016-11-29 15:47
We've seen this error previously when coordinates are so close together they get quantized to the same point (it would still be best if the line builder caught these cases).

Can you provide a direct URL or example data for some of these lines?

**Comment by donflopez** [comment] 2016-11-29 15:49
Of course!

I'll upload a working example, exactly the same of the picture.

Thank you guys! :)

**Comment by dmvaldman** [comment] 2016-11-29 15:53
So far I haven't been able to reproduce this by using Tangram alone to render very short lines

**Comment by dmvaldman** [comment] 2016-11-29 15:54
Tried on this tiny one: https://gist.github.com/anonymous/519b6fa2a6370526a27849f8509ac520

**Comment by dmvaldman** [comment] 2016-11-29 19:11
Looks like this is a problem with repeated points in your line data. Tangram internally skips these when it draws lines, but your data has 4443 repeated indices in its line data (at the zoom level I was looking at). It may be that there are lines of only repeated indices, or something like that, that are causing these problems.

**Comment by nvkelso** [comment] 2016-11-29 19:15
I’ve found http://mapshaper.org to be useful to remove duplicate points in
source geometry. Might give that a whirl and retest?

**Comment by dmvaldman** [comment] 2016-11-29 19:17
Ah, it seems your line data repeats the last point twice! The riddle is unraveling... This may be something Tangram doesn't check for

**Comment by dmvaldman** [comment] 2016-11-29 19:35
Yep. We'll have a fix soon. Thanks for bringing this to our attention.

<img width="586" alt="screen shot 2016-11-29 at 2 34 16 pm" src="https://cloud.githubusercontent.com/assets/796394/20725778/f4de7eba-b640-11e6-9d71-a06620134b1f.png">

**Comment by donflopez** [comment] 2016-11-29 20:16
You're welcome! Great! It has been very quick :) thank you!

**Comment by bcamper** [comment] 2016-11-29 20:53
@donflopez you guys should definitely fix the source data though :)

**Comment by donflopez** [comment] 2016-11-30 09:22
Yes! We have to fix it, thanks for everything :)

**Comment by donflopez** [comment] 2016-12-02 10:38
Should I close this issue? I'm working with the master branch and it is working perfectly. No more strange lines caused by the duplicity in our .mvt datasource.

**Comment by bcamper** [comment] 2016-12-02 15:21
I usually leave these tickets open until the issue is resolved in a public release (will be v0.11.1), so that we can do a final verification pass before closing. Thanks!

**Comment by donflopez** [comment] 2016-12-02 15:22
To you! :)

**Comment by bcamper** [comment] 2016-12-05 22:12
Released in v0.11.1.

**Closed by bcamper** 2016-12-05 22:12 UTC
