### ISSUE TITLE
Last setDataSource() removes other layer interactivity

### ISSUE THREAD

**Issue by michaelhornak** [tangrams/tangram#552] opened 2017-04-27 08:41 UTC
Hi, 
I am having an issue while working with one Tangram.leafletLayer with hover and click events set. This layer has two layers (points, lines), which I am updating once in a while with scene.setDataSource() method. They update separately, so first setDataSource('markers', data) for markers is executed and then in a second or two, scene.setDataSource('lines', data) for lines is executed. 

The issue is, that when second setDataSource() on lines is called, all events on markers stops listening and no hover or click event works on markers layer. Events work only on lines. On next refresh when markers are set, the events start working but only to a time when lines are set and after that they stop listening.

I have set an example page here: [url](http://flww_tangram.ai-maps.com/)

There is a simulation in which every 5 seconds setDataSource() on markers is done, and after 2 seconds setDataSource() on line is done. There is console.log after every setDataSource() methods for markers and lines, and also on click and hover events.

You can see the issue when you hover over markers afted they are added and see hover evens coming trough, but after lines are added no hover events on markers comes trough until another setDataSource() is called on them. 

Is there something I am doing wrong, or it is bug? Thank you very much.

**Comment by bcamper** [comment] 2017-04-27 14:23
Confirmed this looks like a bug, thanks for the detailed report! The internal feature selection mapping is being reset each time the scene is rebuilt, but it should be partitioned by data source.

**Comment by bcamper** [comment] 2017-04-27 16:28
Fixed in db6eb6c17fde93727ee206dc5362234277a8e9d8

@michaelhornak: you should be able to test this fix here - I tried a similar example locally, but please do let me know if you have a chance to verify:

https://precog.mapzen.com/tangrams/tangram/master/dist/tangram.debug.js

**Comment by meetar** [comment] 2017-04-27 17:25
A+ 💯 bug report 👍👍

**Comment by michaelhornak** [comment] 2017-04-27 17:53
great job @bcamper! I confirm its working now on my example too. Thanks very much for really quick reaction 👍

**Comment by bcamper** [comment] 2017-04-28 15:22
This is released in [v0.12.3](https://github.com/tangrams/tangram/releases/tag/v0.12.3).

**Closed by bcamper** 2017-04-28 15:22 UTC
Labels: bug
